In [1]:
import torch
import numpy as np
from torchvision import transforms
import random

In [4]:
torch.randn(5)

tensor([ 0.3813, -1.1712, -0.4844,  1.3131,  1.6718])

In [5]:
torch.tensor(np.random.normal(0, 0.01, size=(5)),
                       dtype=torch.float32)

tensor([-0.0025,  0.0006, -0.0007,  0.0029,  0.0037])

In [11]:
print(random.choice([1,2,3]))

1


In [17]:
a = torch.tensor([[1,2],[2,3]],dtype=float)
print((a!=0).sum(0))
a.mean(dim=0)

tensor([2, 2])


tensor([1.5000, 2.5000], dtype=torch.float64)

In [18]:
data = np.random.randint(0, 255, size=300)
print(data)
img = data.reshape(10,10,3)
print(img.shape)
img_tensor = transforms.ToTensor()(img) # 转换成tensor
print(img_tensor)

[201  48 129 221 251 246  50 194  91  61  98  87  15  18  36  95   3 149
 131 137 149 121  83 247 237 169  79 167 246 113 130 214 171  93  84  63
 152 248 105 130 102 209 204 245 175  42 153  32 203  37 143 153  87 233
  58 183 229 182 204  16  72 179 228 188 161 200  52  68   4 194  94 243
 210 240  43  70 237 139 164 214 251 107 234 121 246 207 191 236 229 119
 216 238 220 137  34   5  68 184  63  37 202 152 219 188 162  40 237 207
 127 148 230 110 147  79 120 243 138 140 215 146  26 154 249  49 136  17
 134 227 235 242   1 208 104   7 254  42 196 245 160  41 231 183 122 140
  12 130   3 241 228 202 182 215 153 158 224 217  98 243 195 111  92  92
 169 159  91 232  34 253 218 171  53 149 226  74  33 143 161 230 135 159
  13  86 252 212  47 127 198  10  91 162  89   3  69  23 128   5  43 236
  55  55   4  20 158 239 221 121 115 114   9 132 125 168  96  49 199  55
 236 218 109 112 145 206  35 222 220  57 173 233 227 116 127  21  75 108
 181  14  57 188  40  10   0 217  32   0 248   1 13

In [7]:
print((a!=1).sum(1))

tensor([1, 2])


In [6]:
print(slice(1,5))

slice(1, 5, None)


In [8]:
a = torch.randn(1,2,3)
print(a)
# print(a[slice(1,5),:])

tensor([[[ 1.6733, -1.6786, -0.5462],
         [ 1.2425, -0.1384,  1.5760]]])


In [12]:
print(a[slice(1,5),:])

tensor([[ 0.4075,  0.5648,  0.3735, -0.4688, -1.2602,  0.7360, -1.2127,  0.3659,
          2.2086, -1.1140,  1.1271],
        [ 0.1354, -1.0377,  1.9350, -0.7969,  1.3153, -0.8429,  1.6227, -0.2585,
         -1.0144, -0.3480,  0.7665],
        [ 0.8499,  1.4345,  0.2676, -0.4927, -2.2076,  1.0837,  0.7890, -0.7827,
         -0.4112,  0.0759, -0.5232],
        [ 0.6127,  0.7109, -0.9012, -0.1604, -0.1981, -1.8700,  0.0192,  0.7330,
         -0.0257,  1.3321,  1.0055]])


In [2]:
a  = torch.Tensor([[1],[2]])
a

tensor([[1.],
        [2.]])

In [3]:
print(a.shape)
print(a.shape[-1])

torch.Size([2, 1])
1


In [4]:
b = torch.Tensor([1])
print(a+b)

tensor([[2.],
        [3.]])


In [17]:
a = torch.randn(1,11)
a

tensor([[ 0.6332, -1.5131,  1.3455, -1.6110, -1.7969, -2.5992, -0.1017,  0.8763,
          0.9414, -1.9822, -0.1544]])

In [18]:
print(a.view(-1,2))

RuntimeError: shape '[-1, 2]' is invalid for input of size 11

In [5]:
a = torch.zeros(5)
a

tensor([0., 0., 0., 0., 0.])

In [6]:
a = torch.LongTensor([1,2])
a

tensor([1, 2])

In [7]:
a.view(-1)

tensor([1, 2])

In [8]:
a

tensor([1, 2])

In [2]:
#-*-coding:utf-8-*-
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
 
 
 
# define model
class TheModelClass(nn.Module):
    def __init__(self):
        super(TheModelClass,self).__init__()
        self.conv1 = nn.Conv2d(3,6,5)
        self.pool = nn.MaxPool2d(2,2)
        self.conv2 = nn.Conv2d(6,16,5)
        self.fc1 = nn.Linear(16*5*5,120)
        self.fc2 = nn.Linear(120,84)
        self.fc3 = nn.Linear(84,10)
 
    def forward(self,x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1,16*5*5)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
 
# initial model
model = TheModelClass()
 
#initialize the optimizer
optimizer = optim.SGD(model.parameters(),lr=0.001,momentum=0.9)
 
# print the model's state_dict
print("model's state_dict:")
print(model.state_dict().keys())
for param_tensor in model.state_dict():
    print(param_tensor,'\t',model.state_dict()[param_tensor].size())
 
print("\noptimizer's state_dict")
for var_name in optimizer.state_dict():
    print(var_name,'\t',optimizer.state_dict()[var_name])
 
print("\nprint particular param")
print('\n',model.conv1.weight.size())
print('\n',model.conv1.weight)
 
print("------------------------------------")
torch.save(model.state_dict(),'./model_state_dict.pt')
# model_2 = TheModelClass()
# model_2.load_state_dict(torch.load('./model_state_dict'))
# model.eval()
# print('\n',model_2.conv1.weight)
# print((model_2.conv1.weight == model.conv1.weight).size())
## 仅仅加载某一层的参数
conv1_weight_state = torch.load('./model_state_dict.pt')['conv1.weight']
print(conv1_weight_state==model.conv1.weight)
 
model_2 = TheModelClass()
model_2.load_state_dict(torch.load('./model_state_dict.pt'))
model_2.conv1.requires_grad=False
print(model_2.conv1.requires_grad)
print(model_2.conv1.bias.requires_grad)

model's state_dict:
odict_keys(['conv1.weight', 'conv1.bias', 'conv2.weight', 'conv2.bias', 'fc1.weight', 'fc1.bias', 'fc2.weight', 'fc2.bias', 'fc3.weight', 'fc3.bias'])
conv1.weight 	 torch.Size([6, 3, 5, 5])
conv1.bias 	 torch.Size([6])
conv2.weight 	 torch.Size([16, 6, 5, 5])
conv2.bias 	 torch.Size([16])
fc1.weight 	 torch.Size([120, 400])
fc1.bias 	 torch.Size([120])
fc2.weight 	 torch.Size([84, 120])
fc2.bias 	 torch.Size([84])
fc3.weight 	 torch.Size([10, 84])
fc3.bias 	 torch.Size([10])

optimizer's state_dict
state 	 {}
param_groups 	 [{'lr': 0.001, 'momentum': 0.9, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'params': [139679427056976, 139679427057136, 139679427057216, 139679427057296, 139679427057376, 139679427057456, 139679427057536, 139679427057616, 139679427057696, 139679427057776]}]

print particular param

 torch.Size([6, 3, 5, 5])

 Parameter containing:
tensor([[[[ 0.0265, -0.0381,  0.0153, -0.0750, -0.1002],
          [-0.0678,  0.0147,  0.0970, -0.0746, -

In [6]:
# def softmax(X):
#     X_exp = X.exp()
#     partition = X_exp.sum(dim=1, keepdim=True)
#     # print("X size is ", X_exp.size())
#     # print("partition size is ", partition, partition.size())
#     return X_exp / partition  # 这里应用了广播机制

In [7]:
# softmax([-2 -1, 0])

AttributeError: 'list' object has no attribute 'exp'

In [8]:
import re
print(re.sub('[^a-z]+', ' ','it is true'))

it is true


In [9]:
print(re.sub('[^a-z]+', ' ','5it is true'))

 it is true


In [10]:
print(re.sub('[^a-z]+', ' ','it is true'))

  is true
